version: 2
jobs:
  one:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - run: sudo pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: echo "Running name.py script"
      - run: python name.py
  two:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - run: sudo pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: echo "Running dice.py script"
      - run: python dice.py
     
     
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
