version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - run: sudo pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: python name.py
